### ISSUE TITLE
Document what context.Context passed to actions does

### ISSUE THREAD

**Issue by soypat** [qmuntal/stateless#28]
I'm using stateless and there is nothing on the context passed to the action.

Does it cancel? When does it cancel? Do errors cancel it?

**Comment by qmuntal** [comment]
The `Fire` context parameter is passed down to all user defined callbacks and there isn't any place where the context error is check. This means that as of today is the user responsibility to implement context error handling.

I'll add some docs for this topic in the next release, and feel free to submit a proposal if you think `stateless` could improve on this area.
