### ISSUE TITLE
How to get the super state of hierarchical state?

### ISSUE THREAD

**Issue by kaundinya5** [qmuntal/stateless#58]
I have states called `in_review`,`verifying` and `waiting_for_decisions` that are all a substate of `processing`. I want the user to only know that it's in processing if it's in any of these substates. I know that I can do `IsInState` and verify if it's processing. But is there a way to directly get the super state for all of the substates?

**Comment by qmuntal** [comment]
`IsInState` (and `IsInStateCtx`) should return true if the current state is equal to, or a substate of, the supplied state, so if I understand correctly it will already work for your use-case.

**Comment by qmuntal** [comment]
@kaundinya5 IMO writing a switch case that customizes what you want to display to your clients is not a bad solution. I would rather not grow `stateless` trying to cover the visualization needs of each use case, but just provide the foundations so users can do it themselves.

**Comment by kaundinya5** [comment]
Ah, okay. Do let me know if I can create a PR with this functionality.
