### ISSUE TITLE
Allow adding actions for leaving a state with a specific trigger

### ISSUE THREAD

**Issue by Metamogul** [qmuntal/stateless#75]
Currently it is possible to configure states to perform an action when entering them, as well as setting a specific action when entering them from a specific transition (`config.go:145`):

```go
func (sc *StateConfiguration) OnEntryFrom(trigger Trigger, action ActionFunc) *StateConfiguration {
	sc.sr.EntryActions = append(sc.sr.EntryActions, actionBehaviour{
		Action:      action,
		Description: newinvocationInfo(action),
		Trigger:     &trigger,
	})
	return sc
}
```

However this is not possible when leaving states with a specific transition. I propose to amend this feature.

**Comment by Metamogul** [comment]
@qmuntal, do you have any objections or do you see this addition not fit to meet your goals with the library? Please let me know if this PR needs changes to be added to the project.

**Comment by qmuntal** [comment]
Thanks for submitting this request. It does make sense, will review the PR soon.
